language: node_js
node_js:
- 6
install:
- npm install
- npm install -g mocha
deploy:
  provider: npm
  on:
    tags: true
  api_key:
    secure: YiF+3Bi279ZTAgWREEI5vOyEShHfYwRPityPiV94lH7qnNVRx1kEZhrjR9/YSfOikTGYVbiH3TUZSijIlNd/ueHidQH0MjhO9WcEEtp08VJG3b1+mte34YrCRoMzSAQHKzwa8F7+x0NIUemV6Ofri3qHJgpo/rYZ0YgOrmOZaZcTP8uVe4DrC7ze5kissDnGWmz5jHS1ek/J0lN+Yr7Z7nw8v+b1K2PbYW/t3KkMNZaESGptl+J0q1wVrP5zT64mrPQmgRaohq8CVBR7ZUSdtIhdsU2WD8Wl5EEa/RzLndC9nKW19mwieUS7nsU5SfLptH3LUZJAXzLYX70Ggyzxv47HSSn5/lvPz73eytmopIDHmubpBxNhNPSfwEg2AbbRMNqrXUc/pE0FImaM+9g1NfnYmkwvDr5MeVvn66sRw87YPDZjXLl/7AFu5k6E82L6Aipqa95FGETJYhpHzMbiqhzHq4Bm7J8ixxNCAd6gK/Wj/Z+mZtrfBw532GCk2Sn/3uG7BbYOpj7Tczna9F6EeYEfrP1sFRQzvctCbkjvYGM2ju4JmgJ35Hs4GMwzdJqefETpDOGuNznT8FehUxjLsHT0IvZG6osp8UE++9TVIC4fHPlxbxin3DqTRN8UQ/j3biUMWBaZlOSeQwO9j5BqVf3o1Qhu00Oylh6OTZ/UrGQ=
  email:
    secure: g8t1RYZDaQtMgfLqRtv0O9CUm1xdojpAzHIawYjARvJVHdkY7pP8TOyBL2tb7FJSrOzwZt9BFCbG5yW2jtdrYWYr7YYYm3GOmX55vavN7K+fO14q0fZO1iSviKjZUMCuyh7dHg2aZ3C7m3qQyJ1WDlXjuBTOp0k338BrMODsDEV7Lkfbh45bW+MYaej+g3MAU61j21QoudSS7SPwcOtdSy0HseyHvSmYGDK7DExWJaUj6KCHWWGFczZOBjm+FfElooVAiS77EwJznOXwNBLdcABBp9MJNqaun2oPYplmpfSoyQ5wS9jYxnrxs6Z1y3XAs2hdhVMZh+EjB/XDilOcEhGNJn+r0k/FU2omO+ov08Caci5o2YJ1PTI+5OGIqcPCrT/Dy91ih1gVNV51fWRAkYEPs3b+RHiWtOjGRlVJnt2INHcNAziOEy8qDT4+ApB0NL5y56LqhYSBgx4juhDSKsYSFsSEd/GTPUHKTdf2AhDoB58eeukAInwdvWMTYeIOr7acnzWmpA6lKLCTeKNvijA769oJkAu6FDAw6CSx2lWCl8dHAvHMt3t4mK6IYoBhGEUdfKhoe4mzZibA5LZ5Q3CnJ5GVdGvSUAqhEcHe2EU/OQnspcc+7+YoARYVpy57Vz9zQyv4VLWSjJpurF910s0DnS4aqI+nV+ai/xtdKSE=
